todo_list/todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'
urlpatterns = [
    path('todo/', views.todo_list_view, name='todo_list_view'),
    path('todo/add/', views.todo_list_edit, name='todo_add'),
    path('todo/mod/<int:todo_id>/', views.todo_list_edit, name='todo_edit'),
    path('todo/del/<int:todo_id>/', views.todo_list_delete, name='todo_del'),
]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

todo_list/todo/models.py
from django.db import models

# Create your models here.
class ToDo(models.Model):
    # タスクID
    id = models.IntegerField(verbose_name='タスクID', primary_key=True)

    # 期限
    deadline = models.DateTimeField(verbose_name='期限')

    # タスク名
    title = models.TextField(verbose_name='タスク名', max_length=255)

    # タスク詳細
    content = models.TextField(verbose_name='タスク詳細', max_length=255, blank=True)

    def __str__(self):
        return self.title


todo_list/todo/forms.py
from django.forms import ModelForm
from todo.models import ToDo

class ToDoForm(ModelForm):

    class Meta:
        # データを登録したいモデルを指定する。
        model = ToDo

        # フォームで入力したいデータを指定する。
        fields = ('deadline', 'title', 'content')

todo_list/todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.list import ListView

from todo.models import ToDo
from todo.forms import ToDoForm

# Create your views here.

def todo_list_view(request):
    # 期限の近い順に並べる
    todo = ToDo.objects.all().order_by('deadline')
    return render(request,
        'todo/todo_list_view.html',
        {'todo':todo}
    )


def todo_list_add(request):
    return HttpResponse("タスク追加")

def todo_list_edit(request, todo_id=None):
    # todo_idが指定されている場合⇒todo項目の修正
    if todo_id:
        todo = get_object_or_404(klass=ToDo, pk=todo_id)

    # todo_idが指定されていない⇒todo項目の追加
    else:
        todo = ToDo()

    if request.method == 'POST':
        form = ToDoForm(request.POST, instance=todo)

        # フォームのバリデーションの実行
        if form.is_valid():
            todo = form.save(commit=False)
            todo.save()
            return redirect('todo:todo_list_view')
    else:
        form = ToDoForm(instance = todo)

    return render(request, 'todo/todo_edit.html', dict(form=form, todo_id=todo_id))

def todo_list_delete(request, todo_id=None):
    todo = get_object_or_404(ToDo, pk=todo_id)
    todo.delete()
    return redirect('todo:todo_list_view')


todo_list/todo/templates/todo/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'todo/css/bootstrap.min.css' %}" >
    {% block extra_css %} {% endblock %}
    <title>{% block title %} TodoList {% endblock %}{</title>
</head>
<body>
    <div class="container"/>
        {% block content %}
        {{ content }}
        {% endblock %}
    </div>
    <script src="{% static 'todo/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'todo/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

todo_list/todo/templates/todo/todo_edit.html
{% extends "todo/base.html"%}
{% load bootstrap4 %}

{% block title %} タスクの編集 {% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">タスクの編集</h4>

    {% if todo_id %}
    <form action="{% url 'todo:todo_edit' todo_id=todo_id %}" method="post">
    {% else %}
    <form action="{% url 'todo:todo_add' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="submit" class="btn btn-primary">送信</button>
            </div>
        </div>
    </form>

    <a href="{% url 'todo:todo_list_view' %}" class="btn btn-secondary btn-sm">戻る</a>

{% endblock content %}

todo_list/todo/templates/todo/todo_list_view.html
{% extends "todo/base.html" %}

{% block title %} 締切の速い順にタスクを並べた {% endblock title%}


{% block content %}

<h4 class="mt-4 border-bottom">タスク一覧</h4>
<a href="{% url 'todo:todo_add' %}" class="btn btn-primary btn-sm my-3"> 追加 </a>
<table class="table table-striped table-bordered">
    <thead>
        <th scope="col">タスクID</th>
        <th scope="col">期限</th>
        <th scope="col">タスク名</th>
        <th scope="col">タスクID</th>
    </thead>
    <tbody>
        {% for item in todo %}
            <tr>
                <td scope="row">{{ item.id }}</th>
                <td>{{ item.deadline }}</th>
                <td>{{ item.title }}</th>
                <td>{{ item.content }}</td>
                <td>
                    <a href="{% url 'todo:todo_edit' todo_id=item.id %}" class="btn btn-outline-primary btn-sm">修正</a>
                    <a href="{% url 'todo:todo_del' todo_id=item.id %}" class="btn btn-outline-danger btn-sm">削除</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content%}