board_project/board_project/board_app/urls.py
from django.urls import path
from .views import signupfunc, loginfunc, listfunc, logoutfunc, detailfunc, goodfunc, readfunc, BoardCreate
from django.conf import settings
from django.conf.urls.static import static

app_name = "board_app"
urlpatterns = [
    path('signup/', signupfunc, name="signup"),
    path('login/', loginfunc, name="login"),
    path('list/', listfunc, name="list"),
    path('logout/', logoutfunc, name="logout"),
    path('detail/<int:pk>', detailfunc, name="detail"),
    path('good/<int:pk>', goodfunc, name="good"),
    path('read/<int:pk>', readfunc, name="read"),
    path('create/', BoardCreate.as_view(), name="create"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board_project/board_project/board_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board_app.urls'))
]

board_project/board_project/board_app/models.py
from django.db import models

# Create your models here.
class BoardModel(models.Model):
  title = models.CharField(max_length=100)
  content = models.TextField()
  author = models.CharField(max_length=100)
  image = models.ImageField(upload_to='')
  good = models.IntegerField(blank=True, null=True, default=0)
  read = models.IntegerField(blank=True, null=True, default = 0)
  readtext = models.CharField(max_length = 100, null=True, blank=True, default="a")


board_project/board_project/board_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import BoardModel
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.urls import reverse_lazy

# Create your views here.
def signupfunc(request):
  if request.method == 'POST':
    username2 = request.POST['username']
    password2 = request.POST['password']
    try:
      User.objects.get(username=username2)
      return render(request, 'signup.html', {'error': 'このユーザは登録されています。'})
    except:
      user = User.objects.create_user(username2, password2)
      return render(request, 'signup.html', {"some": 200})
    
  else:
    print("this is not post method")
  return render(request, 'signup.html', {"some": 100})

def loginfunc(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return redirect("board_app:login")
    else:
        # Return an 'invalid login' error message.
        return redirect("board_app:list")
  return render(request, 'login.html', )

@login_required()
def listfunc(request):
  object_list = BoardModel.objects.all()
  return render(request, 'list.html', {'object_list': object_list})

def logoutfunc(request):
    logout(request)
    return redirect('board_app:login')
    # Redirect to a success page.

def detailfunc(request, pk):
  object = BoardModel.objects.get(pk=pk)
  return render(request, 'detail.html', {'object': object })

def goodfunc(request, pk):
  post = BoardModel.objects.get(pk=pk)
  post.good += 1
  post.save()
  return redirect('board_app:list')

def readfunc(request, pk):
  post = BoardModel.objects.get(pk=pk)
  post2 = request.user.get_username()
  if post2 in post.readtext:
    return redirect('board_app:list')
  else:
    post.read += 1
    post.readtext = post.readtext + ' ' + post2
    return redirect(('board_app:list'))


class BoardCreate(CreateView):
  template_name = 'create.html'
  model = BoardModel
  fields = ('title', 'content', 'image', 'author')
  success_url = reverse_lazy('board_app:list')

board_project/board_project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block extracss %}
    {% endblock extracss %}

    <title>Hello, world!</title>
  </head>
  <body>

    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block extrajs %}
    {% endblock extrajs %}
  </body>
</html>

board_project/board_project/templates/create.html
{% extends 'base.html'%}
{% block content %}

{% if user.is_authenticated %}
<form action='' method='post' enctype="multipart/form-data">
{% csrf_token %} 
  <p>タイトル: <input type="text" name="title"></p>
  <p>内容: <input type="text" name="content"></p>
  <p><input type="file" name="image" ></p>
  <input type="hidden" name="author" value="{{ user.username }}">
  <input type="submit" value="作成する" >
  
</form>
{% else  %}
  <p>ログインしてください</p>
{% endif %}
{% endblock content %}

board_project/board_project/templates/detail.html
{% extends 'base.html' %}

{% block extracss %}

{% endblock extracss %}

{% block header %}
<div class="alert alert-primary" role="alert">
  個別投稿
</div>
{% endblock header %}

{% block content %}
<div class="container">
  <div class="alert alert-primary" role="alert">
    <p>タイトル: {{ object.title }}</p>
    <p>投稿者: {{ object.author }}</p>
    <p>内容: {{ object.content }}</p>
    <p><img src = "{{ object.image.url  }} " width="300"></p>
    <a href="{% url 'board_app:good' object.pk %}" class="btn btn-primary btn active" role="button" aria-pressed="true">いいね {{ object.good }}</a>
    <a href="{% url 'board_app:read' object.pk %}" class="btn btn-secondary btn active" role="button" aria-pressed="true">既読 {{ object.read }}</a>
  </div>
</div>
{% endblock content %}

{% block extrajs %}
{% endblock extrajs %}

board_project/board_project/templates/list.html
{% extends 'base.html' %}

{% block extracss %}

{% endblock extracss %}

{% block header %}
<div class="alert alert-primary" role="alert">
  社内SNS
</div>
{% endblock header %}

{% block content %}
<div class="container">
{% for item in object_list %}

  <div class="alert alert-primary" role="alert">
  <p>タイトル: <a href="{% url 'board_app:detail' item.pk %}">{{ item.title }}</a></p>
  <p>投稿者: {{ item.author }}</p>
  <a href="#" class="btn btn-primary btn active" role="button" aria-pressed="true">いいね {{ item.good }}</a>
  <a href="#" class="btn btn-secondary btn active" role="button" aria-pressed="true">既読 {{ item.read }}</a>
  </div>
{% endfor %}
  <a href="{% url 'board_app:logout' %}">ログアウト</a>
</div>
{% endblock content %}

{% block extrajs %}
{% endblock extrajs %}

board_project/board_project/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href = "{% static 'style.css'%}" >
{% endblock extracss %}

{% block content %}
    <form class="form-signin" method="post">
    {% csrf_token %}
    <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="inputUsername" class="sr-only">User Name</label>
    <input type="text" id="inputUsername" class="form-control" placeholder="username" name="username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
      <div class="checkbox mb-3">
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Login
    </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
  </form>
{% endblock content%}

board_project/board_project/templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href = "{% static 'style.css'%}" >
{% endblock extracss %}

{% block content %}
    <form class="form-signin" method="POST">
    {% csrf_token %}
    <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="inputEmail" class="sr-only">User Name</label>
    <input type="text" id="inputEmail" class="form-control" placeholder="username" name="username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
      <div class="checkbox mb-3">
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Sign in
    </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
  </form>
{% endblock content %}